### ISSUE TITLE
Point scheduled notifications to new mood form

### ISSUE THREAD

**Issue by rymndhng** [UrbanOpus/tribe-client#23]
When clicking on a scheduled notification, it goes to the mood page -- instead it should point to the mood submission form.

Related to #18

**Comment by FaideWW** [comment]
I couldn't get local notifications to work at all; even when scheduling them directly using `$localNotificationService.scheduleMood()`.  For some reason `service.add()` is failing. 

If we can't get this working, we can schedule another message with GCM.

**Comment by FaideWW** [comment]
See #24.
