### ISSUE TITLE
Fix scheduled mood notifications

### ISSUE THREAD

**Issue by FaideWW** [UrbanOpus/tribe-client#24]
Mood notifications are not being properly scheduled.  Not sure what the solution is here, but as a contingency we can schedule notifications with GCM via the backend server.

**Comment by rymndhng** [comment]
Hmm, I wonder if it's related to a cordova plugin related issue. I did have to wrangle some stuff to make it work.

It's working on my build. Give this a shot, if it works then it's probably a configuration issue.
http://cl.ly/3F1h1D371v0F
