### ISSUE TITLE
feature:time format is weird. 

### ISSUE THREAD

**Issue by calderonroberto** [UrbanOpus/tribe-client#29]
Does 12:00 mean am or pm. Is it 24 or 12 format. Also. I set it to remind me at "9" and it accepted my response. Either use a drop down menu or perform more sanitation on user input.

**Comment by FaideWW** [comment]
Are you referring to the mood notifications, or the question notifications?

**Comment by calderonroberto** [comment]
Both. And I'm not getting any notifications :(

**Comment by FaideWW** [comment]
Very strange.  The Android time picker is 12-hour format with an AM-PM option, at least on the devices we tested on.  What device/version of Android are you using?  

As for the notifications, are you getting any feedback when you disable/enable mood reminders?

**Comment by calderonroberto** [comment]
Samsung Galaxy Nexus
Android 4.2.1

Yup. No reminders yet.

**Comment by rymndhng** [comment]
Thanks for the feedback Robert. 
Yeah we've been having problems with the built-in datepickers. Each device I've tried: Nexus 5, Samsung S3, Nexus 7 all have different date-picker implementations. 

We are planning to change this to a fixed dropdown in the next release.
