### ISSUE TITLE
Why does the Q of the day show tomorrow

### ISSUE THREAD

**Issue by rlea** [UrbanOpus/tribe-client#33]
This seems to show when you go into today's message, it's visible but 'greyed' - bit confusing

**Comment by rymndhng** [comment]
"greyed" means it's not clicakble. The two button the top allow users to scroll to questions from previous day to look at the response distributions of those questions.

**Comment by rlea** [comment]
it shouldn't show if there is no tomorrow Q available

**Comment by rymndhng** [comment]
Removed it as of 2a0dd42
