### ISSUE TITLE
The Home page should show the visualizations of QotD and mappiness

### ISSUE THREAD

**Issue by rlea** [UrbanOpus/tribe-client#34]
The home page is more like an 'about' page

**Comment by rymndhng** [comment]
Will move content to an 'About' tab for interested parties for now and clear it up for a dashboard.

**Comment by FaideWW** [comment]
I had a tough time getting D3 to cooperate when showing a time-based graph/plot of mood analytics.  Still haven't gotten it quite nailed down.

In the meantime, I have replicated the timeline from the All Moods page and modified it to show the last 24 hours of mood submissions.
