### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by FaideWW** [UrbanOpus/tribe-client#7]
Users should have a method of submitting feedback regarding the application.  

Submitting issues to this GH repository might be the best solution.  Either via API, or just referring users to the issue tracker.

**Comment by rymndhng** [comment]
fairly low priority -- they can also just e-mail us with questions, as long as we add a link to it.

**Comment by rymndhng** [comment]
I added a link to the github repo in the sidebar -- we'll go with that for now
